[package]

name = "piston"
version = "0.2.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "eddyb"
]
keywords = ["piston", "game", "engine", "core"]
description = "The Piston game engine core libraries"
license = "MIT"
repository = "https://github.com/pistondevelopers/piston.git"
homepage = "https://github.com/pistondevelopers/piston"

[lib]

name = "piston"
path = "./src/lib.rs"

[dependencies]
pistoncore-input = "0.1.0"
pistoncore-event = "0.2.0"
pistoncore-window = "0.1.4"
