[package]

name = "pistoncore-window"
version = "0.0.15"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>"
]
keywords = ["window", "game", "piston"]
description = "A library for window abstraction"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/window.git"
homepage = "https://github.com/pistondevelopers/window"

[lib]

name = "window"
path = "src/lib.rs"

[dependencies.pistoncore-input]
git = "https://github.com/pistondevelopers/input"
#version = "0.0.7"

[dependencies.quack]
git = "https://github.com/pistondevelopers/quack"
#version = "0.0.13"

[dependencies]
libc = "0.1"
