[package]

name = "pistoncore-input"
version = "0.0.2"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["keyboard", "mouse", "input"]
description = "A structure for user input"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/input.git"
homepage = "https://github.com/pistondevelopers/input"

[lib]

name = "input"
path = "src/lib.rs"

