[package]

name = "piston"
version = "0.2.1"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "eddyb"
]
keywords = ["piston", "game", "engine", "core"]
description = "The Piston game engine core libraries"
license = "MIT"
repository = "https://github.com/PistonDevelopers/piston.git"
homepage = "https://github.com/PistonDevelopers/piston"

[lib]

name = "piston"
path = "./src/lib.rs"

[dependencies.pistoncore-input]
path = "src/input"
version = "0.1.0"

[dependencies.pistoncore-event]
path = "src/event"
version = "0.2.1"

[dependencies.pistoncore-window]
path = "src/window"
version = "0.1.5"
