[package]

name = "pistoncore-event_loop"
version = "0.0.3"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "bfops",
]
keywords = ["game", "event", "loop"]
description = "A generic event loop for games and interactive applications"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/event_loop.git"
homepage = "https://github.com/pistondevelopers/event_loop"

[lib]

name = "event_loop"
path = "src/lib.rs"

[dependencies.quack]
git = "https://github.com/pistondevelopers/quack"
#version = "0.0.1"

[dependencies.clock_ticks]
git = "https://github.com/tomaka/clock_ticks"
#version = "*"

