[package]

name = "pistoncore-window"
version = "0.0.1"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>"
]
keywords = ["window", "game"]
description = "A library for window abstraction"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/window.git"
homepage = "https://github.com/pistondevelopers/window"

[lib]

name = "window"
path = "src/lib.rs"

[dependencies.pistoncore-input]

git = "https://github.com/pistondevelopers/input"

[dependencies.pistoncore-current]

git = "https://github.com/pistondevelopers/current"

[dependencies.pistoncore-event_loop]

git = "https://github.com/pistondevelopers/event_loop"

