[package]

name = "event"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>"
]

[lib]

name = "event"
path = "src/lib.rs"

[dependencies.input]

git = "https://github.com/PistonDevelopers/input"

