[package]

name = "pistoncore-event_loop"
version = "0.7.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "bfops",
]
keywords = ["game", "event", "loop", "piston"]
description = "A generic event loop for games and interactive applications"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/piston.git"
homepage = "https://github.com/PistonDevelopers/piston"

[lib]

name = "event_loop"
path = "src/lib.rs"

[dependencies.pistoncore-window]
path = "../window"
version = "0.6.0"

[dependencies.pistoncore-input]
path = "../window"
version = "0.4.0"

[dependencies]
clock_ticks = "0.0.6"
piston-viewport = "0.1.0"
